"""
Love Babbar 450 DSA Sheet - Complete Problem Data

Contains all ~450 problems organized by topic with difficulty and tags.
"""

LOVE_BABBAR_450 = [
    # =========================================================================
    # 1. Array (36 problems)
    # =========================================================================
    {
        "topic": "Array",
        "problems": [
            {"title": "Reverse the array", "difficulty": "easy", "tags": ["array"]},
            {"title": "Find the Maximum and Minimum element in an array", "difficulty": "easy", "tags": ["array"]},
            {"title": "Find the Kth max and min element of an array", "difficulty": "medium", "tags": ["array", "sorting", "heap"]},
            {"title": "Sort an array of 0s 1s and 2s", "difficulty": "medium", "tags": ["array", "two-pointers"]},
            {"title": "Move all negative elements to one side of array", "difficulty": "easy", "tags": ["array"]},
            {"title": "Union and Intersection of two sorted arrays", "difficulty": "easy", "tags": ["array", "two-pointers"]},
            {"title": "Cyclically rotate an array by one", "difficulty": "easy", "tags": ["array"]},
            {"title": "Largest sum contiguous subarray", "difficulty": "medium", "tags": ["array", "dynamic-programming"]},
            {"title": "Minimize the maximum difference between heights", "difficulty": "medium", "tags": ["array", "sorting"]},
            {"title": "Minimum number of jumps to reach end of array", "difficulty": "medium", "tags": ["array", "dynamic-programming", "greedy"]},
            {"title": "Find the duplicate in an array of N+1 integers", "difficulty": "medium", "tags": ["array", "two-pointers"]},
            {"title": "Merge two sorted arrays without extra space", "difficulty": "medium", "tags": ["array", "two-pointers"]},
            {"title": "Kadane's Algorithm", "difficulty": "medium", "tags": ["array", "dynamic-programming"]},
            {"title": "Merge Intervals", "difficulty": "medium", "tags": ["array", "sorting"]},
            {"title": "Next Permutation", "difficulty": "medium", "tags": ["array"]},
            {"title": "Count Inversions", "difficulty": "hard", "tags": ["array", "merge-sort"]},
            {"title": "Best Time to Buy and Sell Stock", "difficulty": "easy", "tags": ["array", "dynamic-programming"]},
            {"title": "Find all pairs with a given sum", "difficulty": "easy", "tags": ["array", "hash-table"]},
            {"title": "Common elements in 3 sorted arrays", "difficulty": "easy", "tags": ["array", "two-pointers"]},
            {"title": "Rearrange array in alternating positive and negative items", "difficulty": "medium", "tags": ["array"]},
            {"title": "Find if there is a subarray with 0 sum", "difficulty": "medium", "tags": ["array", "hash-table"]},
            {"title": "Find factorial of a large number", "difficulty": "medium", "tags": ["array", "math"]},
            {"title": "Maximum Product Subarray", "difficulty": "medium", "tags": ["array", "dynamic-programming"]},
            {"title": "Longest Consecutive Subsequence", "difficulty": "medium", "tags": ["array", "hash-table"]},
            {"title": "Find all elements that appear more than n/k times", "difficulty": "medium", "tags": ["array", "hash-table"]},
            {"title": "Maximum profit by buying and selling a stock twice", "difficulty": "hard", "tags": ["array", "dynamic-programming"]},
            {"title": "Find whether an array is a subset of another array", "difficulty": "easy", "tags": ["array", "hash-table"]},
            {"title": "Find the triplet that sum to a given value", "difficulty": "medium", "tags": ["array", "two-pointers"]},
            {"title": "Trapping Rain Water", "difficulty": "hard", "tags": ["array", "two-pointers", "stack"]},
            {"title": "Chocolate Distribution Problem", "difficulty": "easy", "tags": ["array", "sorting"]},
            {"title": "Smallest subarray with sum greater than a given value", "difficulty": "medium", "tags": ["array", "sliding-window"]},
            {"title": "Three way partitioning of an array", "difficulty": "medium", "tags": ["array", "two-pointers"]},
            {"title": "Minimum swaps required to bring elements <= K together", "difficulty": "medium", "tags": ["array", "sliding-window"]},
            {"title": "Minimum number of operations to make an array palindrome", "difficulty": "medium", "tags": ["array", "two-pointers"]},
            {"title": "Median of two sorted arrays of equal size", "difficulty": "hard", "tags": ["array", "binary-search"]},
            {"title": "Median of two sorted arrays of different sizes", "difficulty": "hard", "tags": ["array", "binary-search"]},
        ],
    },
    # =========================================================================
    # 2. Matrix (10 problems)
    # =========================================================================
    {
        "topic": "Matrix",
        "problems": [
            {"title": "Spiral traversal on a Matrix", "difficulty": "medium", "tags": ["matrix", "array"]},
            {"title": "Search an element in a Matrix", "difficulty": "medium", "tags": ["matrix", "binary-search"]},
            {"title": "Find median in a row wise sorted Matrix", "difficulty": "hard", "tags": ["matrix", "binary-search"]},
            {"title": "Find row with maximum number of 1s", "difficulty": "medium", "tags": ["matrix", "binary-search"]},
            {"title": "Print elements in sorted order using row-column wise sorted matrix", "difficulty": "medium", "tags": ["matrix", "heap"]},
            {"title": "Maximum size rectangle of all 1s", "difficulty": "hard", "tags": ["matrix", "stack", "dynamic-programming"]},
            {"title": "Find a specific pair in Matrix", "difficulty": "hard", "tags": ["matrix", "dynamic-programming"]},
            {"title": "Rotate matrix by 90 degrees", "difficulty": "medium", "tags": ["matrix", "array"]},
            {"title": "Kth smallest element in a row-column wise sorted Matrix", "difficulty": "medium", "tags": ["matrix", "heap", "binary-search"]},
            {"title": "Common elements in all rows of a given matrix", "difficulty": "medium", "tags": ["matrix", "hash-table"]},
        ],
    },
    # =========================================================================
    # 3. String (43 problems)
    # =========================================================================
    {
        "topic": "String",
        "problems": [
            {"title": "Reverse a String", "difficulty": "easy", "tags": ["string"]},
            {"title": "Check whether a String is Palindrome or not", "difficulty": "easy", "tags": ["string"]},
            {"title": "Find Duplicate characters in a string", "difficulty": "easy", "tags": ["string", "hash-table"]},
            {"title": "Check whether one string is a rotation of another", "difficulty": "easy", "tags": ["string"]},
            {"title": "Check if two given strings are isomorphic to each other", "difficulty": "easy", "tags": ["string", "hash-table"]},
            {"title": "Count and Say problem", "difficulty": "medium", "tags": ["string"]},
            {"title": "Longest Palindromic Substring", "difficulty": "medium", "tags": ["string", "dynamic-programming"]},
            {"title": "Longest Recurring Subsequence", "difficulty": "medium", "tags": ["string", "dynamic-programming"]},
            {"title": "Print all subsequences of a string", "difficulty": "medium", "tags": ["string", "recursion"]},
            {"title": "Print all permutations of a string", "difficulty": "medium", "tags": ["string", "backtracking"]},
            {"title": "Split Binary String into equal 0s and 1s", "difficulty": "easy", "tags": ["string"]},
            {"title": "Word Wrap Problem", "difficulty": "hard", "tags": ["string", "dynamic-programming"]},
            {"title": "Edit Distance", "difficulty": "medium", "tags": ["string", "dynamic-programming"]},
            {"title": "Find next greater number with same set of digits", "difficulty": "medium", "tags": ["string", "math"]},
            {"title": "Balanced parenthesis checker", "difficulty": "easy", "tags": ["string", "stack"]},
            {"title": "Word Break Problem", "difficulty": "medium", "tags": ["string", "dynamic-programming"]},
            {"title": "Rabin Karp Algorithm for pattern searching", "difficulty": "medium", "tags": ["string"]},
            {"title": "KMP Algorithm for pattern searching", "difficulty": "medium", "tags": ["string"]},
            {"title": "Convert a sentence into its equivalent mobile numeric keypad sequence", "difficulty": "medium", "tags": ["string"]},
            {"title": "Minimum number of bracket reversals needed", "difficulty": "medium", "tags": ["string", "stack"]},
            {"title": "Count palindromic subsequences", "difficulty": "hard", "tags": ["string", "dynamic-programming"]},
            {"title": "Count of number of given string in 2D character array", "difficulty": "medium", "tags": ["string", "matrix", "backtracking"]},
            {"title": "Search a Word in a 2D Grid of characters", "difficulty": "medium", "tags": ["string", "matrix", "backtracking"]},
            {"title": "Boyer Moore Algorithm for pattern searching", "difficulty": "medium", "tags": ["string"]},
            {"title": "Roman Number to Integer", "difficulty": "easy", "tags": ["string", "math"]},
            {"title": "Longest Common Prefix", "difficulty": "easy", "tags": ["string"]},
            {"title": "Minimum number of flips to make binary string alternating", "difficulty": "easy", "tags": ["string"]},
            {"title": "Find the first repeated word in a string", "difficulty": "easy", "tags": ["string", "hash-table"]},
            {"title": "Minimum number of swaps for bracket balancing", "difficulty": "medium", "tags": ["string", "greedy"]},
            {"title": "Longest Common Subsequence", "difficulty": "medium", "tags": ["string", "dynamic-programming"]},
            {"title": "Generate all valid IP addresses", "difficulty": "medium", "tags": ["string", "backtracking"]},
            {"title": "Smallest window that contains all characters of another string", "difficulty": "hard", "tags": ["string", "sliding-window", "hash-table"]},
            {"title": "Rearrange characters so no two adjacent are same", "difficulty": "medium", "tags": ["string", "heap", "greedy"]},
            {"title": "Minimum characters to be added at front to make string palindrome", "difficulty": "hard", "tags": ["string"]},
            {"title": "Print Anagrams together", "difficulty": "medium", "tags": ["string", "hash-table", "sorting"]},
            {"title": "Smallest window containing all characters of another string", "difficulty": "hard", "tags": ["string", "sliding-window"]},
            {"title": "Recursively remove all adjacent duplicates", "difficulty": "medium", "tags": ["string", "stack"]},
            {"title": "Wildcard string matching", "difficulty": "hard", "tags": ["string", "dynamic-programming"]},
            {"title": "Function to find number of customers who could not get a computer", "difficulty": "medium", "tags": ["string", "hash-table"]},
            {"title": "Transform one string to another with minimum operations", "difficulty": "medium", "tags": ["string"]},
            {"title": "Check if two strings are isomorphic", "difficulty": "easy", "tags": ["string", "hash-table"]},
            {"title": "Recursively print all sentences from word lists", "difficulty": "medium", "tags": ["string", "recursion"]},
            {"title": "Check if given string can be split into four distinct strings", "difficulty": "medium", "tags": ["string"]},
        ],
    },
    # =========================================================================
    # 4. Searching and Sorting (36 problems)
    # =========================================================================
    {
        "topic": "Searching and Sorting",
        "problems": [
            {"title": "Find first and last positions of an element in sorted array", "difficulty": "medium", "tags": ["binary-search", "array"]},
            {"title": "Find a fixed point in a given array", "difficulty": "easy", "tags": ["binary-search", "array"]},
            {"title": "Search in a rotated sorted array", "difficulty": "medium", "tags": ["binary-search", "array"]},
            {"title": "Square root of an integer", "difficulty": "easy", "tags": ["binary-search", "math"]},
            {"title": "Maximum and minimum of an array using minimum comparisons", "difficulty": "easy", "tags": ["array"]},
            {"title": "Optimum location of point to minimize total distance", "difficulty": "medium", "tags": ["binary-search", "math"]},
            {"title": "Find the repeating and the missing number", "difficulty": "medium", "tags": ["array", "math"]},
            {"title": "Find majority element", "difficulty": "easy", "tags": ["array", "hash-table"]},
            {"title": "Searching in an array where adjacent differ by at most k", "difficulty": "medium", "tags": ["array"]},
            {"title": "Find a pair with a given difference", "difficulty": "medium", "tags": ["array", "hash-table", "two-pointers"]},
            {"title": "Find four elements that sum to a given value", "difficulty": "medium", "tags": ["array", "hash-table"]},
            {"title": "Maximum sum such that no two elements are adjacent", "difficulty": "medium", "tags": ["array", "dynamic-programming"]},
            {"title": "Count triplets with sum smaller than a given value", "difficulty": "medium", "tags": ["array", "two-pointers", "sorting"]},
            {"title": "Product array puzzle without division", "difficulty": "medium", "tags": ["array"]},
            {"title": "Sort array according to count of set bits", "difficulty": "medium", "tags": ["array", "bit-manipulation", "sorting"]},
            {"title": "Minimum number of swaps required to sort the array", "difficulty": "medium", "tags": ["array", "graph", "sorting"]},
            {"title": "Bishu and Soldiers", "difficulty": "medium", "tags": ["binary-search", "sorting"]},
            {"title": "Rasta and Kheshtak", "difficulty": "medium", "tags": ["bit-manipulation"]},
            {"title": "Kth smallest number in multiplication table", "difficulty": "hard", "tags": ["binary-search"]},
            {"title": "Find the pivot element in sorted rotated array", "difficulty": "medium", "tags": ["binary-search", "array"]},
            {"title": "Kth element of two sorted arrays", "difficulty": "medium", "tags": ["binary-search", "array"]},
            {"title": "Aggressive Cows", "difficulty": "hard", "tags": ["binary-search"]},
            {"title": "Book Allocation Problem", "difficulty": "hard", "tags": ["binary-search"]},
            {"title": "EKO SPOJ", "difficulty": "medium", "tags": ["binary-search"]},
            {"title": "Job Scheduling Algo", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Missing number in Arithmetic Progression", "difficulty": "easy", "tags": ["binary-search", "math"]},
            {"title": "Smallest number with at least n trailing zeroes in factorial", "difficulty": "medium", "tags": ["binary-search", "math"]},
            {"title": "Painters Partition Problem", "difficulty": "hard", "tags": ["binary-search", "dynamic-programming"]},
            {"title": "ROTI Prata SPOJ", "difficulty": "medium", "tags": ["binary-search"]},
            {"title": "Double Helix SPOJ", "difficulty": "medium", "tags": ["array", "two-pointers"]},
            {"title": "Subset Sums", "difficulty": "medium", "tags": ["recursion", "sorting"]},
            {"title": "Find the inversion count", "difficulty": "hard", "tags": ["array", "merge-sort"]},
            {"title": "Merge sort in place", "difficulty": "medium", "tags": ["sorting", "array"]},
            {"title": "Partitioning and sorting arrays with many repeated entries", "difficulty": "medium", "tags": ["sorting", "array"]},
            {"title": "Sort array by frequency", "difficulty": "medium", "tags": ["sorting", "hash-table"]},
            {"title": "Counting sort", "difficulty": "easy", "tags": ["sorting"]},
        ],
    },
    # =========================================================================
    # 5. Linked List (36 problems)
    # =========================================================================
    {
        "topic": "Linked List",
        "problems": [
            {"title": "Reverse a linked list", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Reverse a linked list in groups of K", "difficulty": "medium", "tags": ["linked-list"]},
            {"title": "Detect a loop in linked list", "difficulty": "easy", "tags": ["linked-list", "two-pointers"]},
            {"title": "Delete loop in linked list", "difficulty": "medium", "tags": ["linked-list", "two-pointers"]},
            {"title": "Find the starting point of the loop", "difficulty": "medium", "tags": ["linked-list", "two-pointers"]},
            {"title": "Remove duplicates in a sorted linked list", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Remove duplicates in an unsorted linked list", "difficulty": "medium", "tags": ["linked-list", "hash-table"]},
            {"title": "Move the last element to front of linked list", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Add 1 to a number represented as linked list", "difficulty": "medium", "tags": ["linked-list", "math"]},
            {"title": "Add two numbers represented by linked lists", "difficulty": "medium", "tags": ["linked-list", "math"]},
            {"title": "Intersection of two sorted linked lists", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Intersection point of two linked lists", "difficulty": "medium", "tags": ["linked-list", "two-pointers"]},
            {"title": "Merge sort for linked lists", "difficulty": "medium", "tags": ["linked-list", "sorting"]},
            {"title": "Quicksort for linked lists", "difficulty": "medium", "tags": ["linked-list", "sorting"]},
            {"title": "Middle element of a linked list", "difficulty": "easy", "tags": ["linked-list", "two-pointers"]},
            {"title": "Check if a linked list is circular", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Split a circular linked list into two halves", "difficulty": "medium", "tags": ["linked-list"]},
            {"title": "Check if linked list is palindrome", "difficulty": "medium", "tags": ["linked-list", "two-pointers"]},
            {"title": "Deletion from a circular linked list", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Reverse a doubly linked list", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Find pairs with given sum in doubly linked list", "difficulty": "easy", "tags": ["linked-list", "two-pointers"]},
            {"title": "Count triplets in sorted doubly linked list with sum equal to x", "difficulty": "medium", "tags": ["linked-list"]},
            {"title": "Sort a K sorted doubly linked list", "difficulty": "medium", "tags": ["linked-list", "heap"]},
            {"title": "Rotate doubly linked list by N nodes", "difficulty": "medium", "tags": ["linked-list"]},
            {"title": "Rotate a doubly linked list in groups", "difficulty": "medium", "tags": ["linked-list"]},
            {"title": "Can we reverse a linked list in O(n) time", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Why Quicksort preferred for arrays and Mergesort for linked lists", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Flatten a linked list", "difficulty": "medium", "tags": ["linked-list"]},
            {"title": "Sort a linked list of 0s 1s and 2s", "difficulty": "medium", "tags": ["linked-list"]},
            {"title": "Clone a linked list with next and random pointer", "difficulty": "medium", "tags": ["linked-list", "hash-table"]},
            {"title": "Merge K sorted linked lists", "difficulty": "hard", "tags": ["linked-list", "heap"]},
            {"title": "Multiply two linked lists", "difficulty": "medium", "tags": ["linked-list", "math"]},
            {"title": "Delete nodes with greater value on right", "difficulty": "medium", "tags": ["linked-list"]},
            {"title": "Segregate even and odd nodes in linked list", "difficulty": "medium", "tags": ["linked-list"]},
            {"title": "Nth node from end of linked list", "difficulty": "easy", "tags": ["linked-list"]},
            {"title": "Find the length of loop in linked list", "difficulty": "medium", "tags": ["linked-list", "two-pointers"]},
        ],
    },
    # =========================================================================
    # 6. Bit Manipulation (10 problems)
    # =========================================================================
    {
        "topic": "Bit Manipulation",
        "problems": [
            {"title": "Count set bits in an integer", "difficulty": "easy", "tags": ["bit-manipulation"]},
            {"title": "Find the two non-repeating elements in an array", "difficulty": "medium", "tags": ["bit-manipulation", "array"]},
            {"title": "Count number of bits to be flipped to convert A to B", "difficulty": "easy", "tags": ["bit-manipulation"]},
            {"title": "Count total set bits in all numbers from 1 to n", "difficulty": "medium", "tags": ["bit-manipulation", "math"]},
            {"title": "Check if a number is power of 2", "difficulty": "easy", "tags": ["bit-manipulation"]},
            {"title": "Find position of the only set bit", "difficulty": "easy", "tags": ["bit-manipulation"]},
            {"title": "Copy set bits in a range", "difficulty": "medium", "tags": ["bit-manipulation"]},
            {"title": "Divide two integers without using multiplication division and mod", "difficulty": "medium", "tags": ["bit-manipulation", "math"]},
            {"title": "Calculate square of a number without multiplication or pow", "difficulty": "easy", "tags": ["bit-manipulation", "math"]},
            {"title": "Power Set", "difficulty": "medium", "tags": ["bit-manipulation", "recursion"]},
        ],
    },
    # =========================================================================
    # 7. Greedy (35 problems)
    # =========================================================================
    {
        "topic": "Greedy",
        "problems": [
            {"title": "Activity Selection Problem", "difficulty": "easy", "tags": ["greedy", "sorting"]},
            {"title": "Job Sequencing Problem", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Huffman Coding", "difficulty": "hard", "tags": ["greedy", "heap", "tree"]},
            {"title": "Water Connection Problem", "difficulty": "medium", "tags": ["greedy", "graph"]},
            {"title": "Fractional Knapsack Problem", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Choose minimum number of coins to make a given value", "difficulty": "easy", "tags": ["greedy"]},
            {"title": "Find maximum trains for which stoppage can be provided", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Minimum Platforms Required", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Buy maximum stocks if i stocks can be bought on i-th day", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Find the minimum and maximum amount to buy all N candies", "difficulty": "medium", "tags": ["greedy"]},
            {"title": "Minimize cash flow among friends", "difficulty": "hard", "tags": ["greedy", "graph"]},
            {"title": "Minimum cost of ropes", "difficulty": "easy", "tags": ["greedy", "heap"]},
            {"title": "Check if it is possible to survive on Island", "difficulty": "medium", "tags": ["greedy"]},
            {"title": "Find maximum meetings in one room", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Maximum product subset of an array", "difficulty": "medium", "tags": ["greedy", "array"]},
            {"title": "Maximize sum after K negations", "difficulty": "easy", "tags": ["greedy", "sorting"]},
            {"title": "Maximize sum of arr[i] multiplied by i", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Maximum sum of absolute differences", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Maximize sum of consecutive differences in circular arrangement", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Minimum sum of absolute differences of pairs", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Shortest Job First CPU Scheduling", "difficulty": "medium", "tags": ["greedy"]},
            {"title": "LRU Page Replacement Algorithm", "difficulty": "medium", "tags": ["greedy", "design"]},
            {"title": "Smallest subset with sum greater than all other elements", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Chocolate Distribution Problem", "difficulty": "easy", "tags": ["greedy", "sorting"]},
            {"title": "DEFKIN on SPOJ", "difficulty": "medium", "tags": ["greedy"]},
            {"title": "DIEHARD Problem", "difficulty": "medium", "tags": ["greedy", "dynamic-programming"]},
            {"title": "GERGOVIA Wine trading", "difficulty": "medium", "tags": ["greedy"]},
            {"title": "Picking Up Chicks SPOJ", "difficulty": "medium", "tags": ["greedy"]},
            {"title": "CHOCOLA Chocolate Breaking Problem", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "ARRANGE Amplifiers Problem", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "K Centers Problem", "difficulty": "hard", "tags": ["greedy", "graph"]},
            {"title": "Minimum cost to cut a board into squares", "difficulty": "medium", "tags": ["greedy", "sorting"]},
            {"title": "Minimum number from given sequence", "difficulty": "medium", "tags": ["greedy", "stack"]},
            {"title": "Rearrange characters in string such that no two adjacent are same", "difficulty": "medium", "tags": ["greedy", "heap", "string"]},
            {"title": "Find maximum equal sum of every three stacks", "difficulty": "medium", "tags": ["greedy", "stack"]},
        ],
    },
    # =========================================================================
    # 8. Backtracking (19 problems)
    # =========================================================================
    {
        "topic": "Backtracking",
        "problems": [
            {"title": "Rat in a Maze Problem", "difficulty": "medium", "tags": ["backtracking", "matrix"]},
            {"title": "N Queen Problem", "difficulty": "hard", "tags": ["backtracking"]},
            {"title": "Word Break Problem using Backtracking", "difficulty": "medium", "tags": ["backtracking", "string"]},
            {"title": "Remove Invalid Parentheses", "difficulty": "hard", "tags": ["backtracking", "string", "bfs"]},
            {"title": "Sudoku Solver", "difficulty": "hard", "tags": ["backtracking", "matrix"]},
            {"title": "M Coloring Problem", "difficulty": "medium", "tags": ["backtracking", "graph"]},
            {"title": "Print all palindromic partitions of a string", "difficulty": "medium", "tags": ["backtracking", "string"]},
            {"title": "Subset Sum Problem", "difficulty": "medium", "tags": ["backtracking", "recursion"]},
            {"title": "The Knight's Tour Problem", "difficulty": "hard", "tags": ["backtracking", "matrix"]},
            {"title": "Tug of War", "difficulty": "medium", "tags": ["backtracking", "recursion"]},
            {"title": "Find shortest safe route in a path with landmines", "difficulty": "medium", "tags": ["backtracking", "matrix", "bfs"]},
            {"title": "Combinational Sum", "difficulty": "medium", "tags": ["backtracking", "array"]},
            {"title": "Find Maximum number possible by doing at most K swaps", "difficulty": "medium", "tags": ["backtracking", "string"]},
            {"title": "Print all permutations of a string", "difficulty": "medium", "tags": ["backtracking", "string"]},
            {"title": "Find if there is a path of more than k length from a source", "difficulty": "medium", "tags": ["backtracking", "graph"]},
            {"title": "Longest Possible Route in a Matrix with Hurdles", "difficulty": "medium", "tags": ["backtracking", "matrix"]},
            {"title": "Print all possible paths from top left to bottom right of a mxn matrix", "difficulty": "medium", "tags": ["backtracking", "matrix"]},
            {"title": "Partition of a set into K subsets with equal sum", "difficulty": "medium", "tags": ["backtracking", "recursion"]},
            {"title": "Find the Kth Permutation Sequence", "difficulty": "medium", "tags": ["backtracking", "math"]},
        ],
    },
    # =========================================================================
    # 9. Stacks and Queues (38 problems)
    # =========================================================================
    {
        "topic": "Stacks and Queues",
        "problems": [
            {"title": "Implement Stack from Scratch", "difficulty": "easy", "tags": ["stack", "design"]},
            {"title": "Implement Queue from Scratch", "difficulty": "easy", "tags": ["queue", "design"]},
            {"title": "Implement 2 stacks in an array", "difficulty": "medium", "tags": ["stack", "design"]},
            {"title": "Find the middle element of a stack", "difficulty": "medium", "tags": ["stack"]},
            {"title": "Implement N stacks in an Array", "difficulty": "medium", "tags": ["stack", "design"]},
            {"title": "Check balanced parentheses in expression", "difficulty": "easy", "tags": ["stack", "string"]},
            {"title": "Reverse a string using Stack", "difficulty": "easy", "tags": ["stack", "string"]},
            {"title": "Design a stack that supports getMin in O(1)", "difficulty": "medium", "tags": ["stack", "design"]},
            {"title": "Find the next greater element", "difficulty": "medium", "tags": ["stack", "array"]},
            {"title": "The Celebrity Problem", "difficulty": "medium", "tags": ["stack", "matrix"]},
            {"title": "Arithmetic Expression Evaluation", "difficulty": "medium", "tags": ["stack", "string"]},
            {"title": "Evaluation of Postfix Expression", "difficulty": "medium", "tags": ["stack", "string"]},
            {"title": "Implement a method to insert an element at bottom of stack", "difficulty": "easy", "tags": ["stack", "recursion"]},
            {"title": "Reverse a stack using recursion", "difficulty": "medium", "tags": ["stack", "recursion"]},
            {"title": "Sort a stack using recursion", "difficulty": "medium", "tags": ["stack", "recursion"]},
            {"title": "Merge Overlapping Intervals", "difficulty": "medium", "tags": ["stack", "sorting"]},
            {"title": "Largest rectangular area in a Histogram", "difficulty": "hard", "tags": ["stack"]},
            {"title": "Length of longest valid substring", "difficulty": "hard", "tags": ["stack", "string", "dynamic-programming"]},
            {"title": "Expression contains redundant bracket or not", "difficulty": "medium", "tags": ["stack", "string"]},
            {"title": "Implement Stack using Queue", "difficulty": "easy", "tags": ["stack", "queue"]},
            {"title": "Implement Queue using Stack", "difficulty": "easy", "tags": ["queue", "stack"]},
            {"title": "Implement a Circular Queue", "difficulty": "easy", "tags": ["queue", "design"]},
            {"title": "Implement Deque from Scratch", "difficulty": "medium", "tags": ["queue", "design"]},
            {"title": "Check if stack elements are pairwise consecutive", "difficulty": "easy", "tags": ["stack"]},
            {"title": "Sliding Window Maximum", "difficulty": "hard", "tags": ["queue", "sliding-window", "array"]},
            {"title": "Reverse a Queue using recursion", "difficulty": "easy", "tags": ["queue", "recursion"]},
            {"title": "Reverse first K elements of Queue", "difficulty": "easy", "tags": ["queue"]},
            {"title": "Interleave first half of Queue with second half", "difficulty": "medium", "tags": ["queue"]},
            {"title": "Find the first circular tour that visits all petrol pumps", "difficulty": "medium", "tags": ["queue", "greedy"]},
            {"title": "Minimum time required to rot all oranges", "difficulty": "medium", "tags": ["queue", "bfs", "matrix"]},
            {"title": "Distance of nearest cell having 1 in binary matrix", "difficulty": "medium", "tags": ["queue", "bfs", "matrix"]},
            {"title": "First negative integer in every window of size k", "difficulty": "medium", "tags": ["queue", "sliding-window"]},
            {"title": "Special Stack supporting getMin in O(1)", "difficulty": "medium", "tags": ["stack", "design"]},
            {"title": "Next Greater Frequency Element", "difficulty": "medium", "tags": ["stack", "hash-table"]},
            {"title": "Maximum of all subarrays of size k using Deque", "difficulty": "medium", "tags": ["queue", "sliding-window"]},
            {"title": "Sum of minimum and maximum elements of all subarrays of size k", "difficulty": "medium", "tags": ["sliding-window", "array"]},
            {"title": "Stock Span Problem", "difficulty": "medium", "tags": ["stack", "array"]},
            {"title": "The Celebrity Problem using Stack", "difficulty": "medium", "tags": ["stack"]},
        ],
    },
    # =========================================================================
    # 10. Binary Trees (35 problems)
    # =========================================================================
    {
        "topic": "Binary Trees",
        "problems": [
            {"title": "Level order traversal", "difficulty": "easy", "tags": ["tree", "bfs"]},
            {"title": "Reverse Level Order traversal", "difficulty": "easy", "tags": ["tree", "bfs"]},
            {"title": "Height of a tree", "difficulty": "easy", "tags": ["tree", "dfs"]},
            {"title": "Diameter of a tree", "difficulty": "easy", "tags": ["tree", "dfs"]},
            {"title": "Mirror of a tree", "difficulty": "easy", "tags": ["tree", "dfs"]},
            {"title": "Inorder Traversal of a tree iterative", "difficulty": "medium", "tags": ["tree", "stack"]},
            {"title": "Preorder Traversal of a tree iterative", "difficulty": "medium", "tags": ["tree", "stack"]},
            {"title": "Postorder Traversal of a tree iterative", "difficulty": "hard", "tags": ["tree", "stack"]},
            {"title": "Left View of a tree", "difficulty": "easy", "tags": ["tree", "bfs"]},
            {"title": "Right View of a tree", "difficulty": "easy", "tags": ["tree", "bfs"]},
            {"title": "Top View of a tree", "difficulty": "medium", "tags": ["tree", "bfs"]},
            {"title": "Bottom View of a tree", "difficulty": "medium", "tags": ["tree", "bfs"]},
            {"title": "Zig Zag traversal of a binary tree", "difficulty": "medium", "tags": ["tree", "bfs"]},
            {"title": "Check if a tree is balanced or not", "difficulty": "easy", "tags": ["tree", "dfs"]},
            {"title": "Diagonal Traversal of a Binary tree", "difficulty": "medium", "tags": ["tree", "bfs"]},
            {"title": "Boundary Traversal of a Binary tree", "difficulty": "medium", "tags": ["tree"]},
            {"title": "Construct Binary Tree from Inorder and Preorder", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Construct Binary Tree from Inorder and Postorder", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Construct Binary Tree from string with bracket representation", "difficulty": "medium", "tags": ["tree", "string"]},
            {"title": "Check if two trees are mirror of each other", "difficulty": "easy", "tags": ["tree", "dfs"]},
            {"title": "Check if a tree is symmetric", "difficulty": "easy", "tags": ["tree", "dfs"]},
            {"title": "Lowest Common Ancestor in a Binary Tree", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Minimum distance between two given nodes", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Kth Ancestor of a node in Binary Tree", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Sum of nodes on the longest path", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Check if a Binary Tree contains duplicate subtrees of size 2 or more", "difficulty": "hard", "tags": ["tree", "hash-table"]},
            {"title": "Check if a tree is a Sum Tree", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Check if two trees are Isomorphic", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Largest BST in a Binary Tree", "difficulty": "hard", "tags": ["tree", "dfs"]},
            {"title": "Flatten a Binary Tree to Linked List", "difficulty": "medium", "tags": ["tree", "linked-list"]},
            {"title": "Maximum sum path in Binary Tree", "difficulty": "hard", "tags": ["tree", "dfs"]},
            {"title": "Sum of longest bloodline in Binary Tree", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Expression Tree from Postfix", "difficulty": "medium", "tags": ["tree", "stack"]},
            {"title": "K Sum Paths in Binary Tree", "difficulty": "medium", "tags": ["tree", "hash-table"]},
            {"title": "Check if Binary Tree has duplicate values", "difficulty": "easy", "tags": ["tree", "hash-table"]},
        ],
    },
    # =========================================================================
    # 11. Binary Search Trees (12 problems)
    # =========================================================================
    {
        "topic": "Binary Search Trees",
        "problems": [
            {"title": "Find a value in a BST", "difficulty": "easy", "tags": ["tree", "binary-search"]},
            {"title": "Deletion of a node in BST", "difficulty": "medium", "tags": ["tree", "binary-search"]},
            {"title": "Find Min and Max value in a BST", "difficulty": "easy", "tags": ["tree"]},
            {"title": "Find Inorder Successor and Predecessor in BST", "difficulty": "medium", "tags": ["tree", "binary-search"]},
            {"title": "Check if a tree is a BST or not", "difficulty": "medium", "tags": ["tree", "dfs"]},
            {"title": "Populate Inorder Successor for all nodes", "difficulty": "medium", "tags": ["tree"]},
            {"title": "Find LCA of two nodes in BST", "difficulty": "medium", "tags": ["tree"]},
            {"title": "Construct BST from preorder traversal", "difficulty": "medium", "tags": ["tree", "binary-search"]},
            {"title": "Convert BST to Balanced BST", "difficulty": "medium", "tags": ["tree"]},
            {"title": "Convert sorted linked list to Balanced BST", "difficulty": "medium", "tags": ["tree", "linked-list"]},
            {"title": "Merge two BSTs", "difficulty": "hard", "tags": ["tree"]},
            {"title": "Find Kth largest element in BST", "difficulty": "medium", "tags": ["tree"]},
        ],
    },
    # =========================================================================
    # 12. Graphs (44 problems)
    # =========================================================================
    {
        "topic": "Graphs",
        "problems": [
            {"title": "BFS of a Graph", "difficulty": "easy", "tags": ["graph", "bfs"]},
            {"title": "DFS of a Graph", "difficulty": "easy", "tags": ["graph", "dfs"]},
            {"title": "Detect Cycle in Undirected Graph using BFS", "difficulty": "medium", "tags": ["graph", "bfs"]},
            {"title": "Detect Cycle in Undirected Graph using DFS", "difficulty": "medium", "tags": ["graph", "dfs"]},
            {"title": "Detect Cycle in a Directed Graph using DFS", "difficulty": "medium", "tags": ["graph", "dfs"]},
            {"title": "Detect Cycle in a Directed Graph using BFS", "difficulty": "medium", "tags": ["graph", "bfs", "topological-sort"]},
            {"title": "Topological Sort BFS", "difficulty": "medium", "tags": ["graph", "bfs", "topological-sort"]},
            {"title": "Topological Sort DFS", "difficulty": "medium", "tags": ["graph", "dfs", "topological-sort"]},
            {"title": "Minimum steps by Knight to reach target", "difficulty": "medium", "tags": ["graph", "bfs"]},
            {"title": "Flood Fill Algorithm", "difficulty": "easy", "tags": ["graph", "bfs", "dfs"]},
            {"title": "Clone a Graph", "difficulty": "medium", "tags": ["graph", "dfs", "hash-table"]},
            {"title": "Detect Negative Weight Cycle Bellman Ford", "difficulty": "medium", "tags": ["graph"]},
            {"title": "Number of Islands", "difficulty": "medium", "tags": ["graph", "bfs", "dfs"]},
            {"title": "Check if graph is Bipartite", "difficulty": "medium", "tags": ["graph", "bfs", "dfs"]},
            {"title": "Shortest Path in DAG", "difficulty": "medium", "tags": ["graph", "topological-sort"]},
            {"title": "Strongly Connected Components Kosaraju", "difficulty": "hard", "tags": ["graph", "dfs"]},
            {"title": "Dijkstra's Algorithm", "difficulty": "medium", "tags": ["graph", "heap"]},
            {"title": "Bellman Ford Algorithm", "difficulty": "medium", "tags": ["graph"]},
            {"title": "Floyd Warshall Algorithm", "difficulty": "medium", "tags": ["graph"]},
            {"title": "Travelling Salesman Problem", "difficulty": "hard", "tags": ["graph", "dynamic-programming"]},
            {"title": "Graph Coloring Problem", "difficulty": "medium", "tags": ["graph", "backtracking"]},
            {"title": "Snake and Ladder Problem", "difficulty": "medium", "tags": ["graph", "bfs"]},
            {"title": "Find bridges in a graph", "difficulty": "hard", "tags": ["graph", "dfs"]},
            {"title": "Steps to reach target using BFS", "difficulty": "medium", "tags": ["graph", "bfs"]},
            {"title": "Word Boggle", "difficulty": "medium", "tags": ["graph", "backtracking", "matrix"]},
            {"title": "Longest path in a DAG", "difficulty": "medium", "tags": ["graph", "topological-sort", "dynamic-programming"]},
            {"title": "Journey to the Moon", "difficulty": "medium", "tags": ["graph", "union-find"]},
            {"title": "Cheapest Flights Within K Stops", "difficulty": "medium", "tags": ["graph", "dynamic-programming"]},
            {"title": "Oliver and the Game", "difficulty": "medium", "tags": ["graph", "dfs"]},
            {"title": "Water Jug Problem using BFS", "difficulty": "medium", "tags": ["graph", "bfs"]},
            {"title": "Find if there is a path between two vertices", "difficulty": "easy", "tags": ["graph", "bfs", "dfs"]},
            {"title": "Course Schedule", "difficulty": "medium", "tags": ["graph", "topological-sort"]},
            {"title": "Minimum Cost Path", "difficulty": "medium", "tags": ["graph", "dynamic-programming"]},
            {"title": "Circle of Strings", "difficulty": "medium", "tags": ["graph"]},
            {"title": "Euler Circuit in an undirected graph", "difficulty": "medium", "tags": ["graph"]},
            {"title": "Alien Dictionary", "difficulty": "hard", "tags": ["graph", "topological-sort"]},
            {"title": "Number of Operations to Make Network Connected", "difficulty": "medium", "tags": ["graph", "union-find"]},
            {"title": "Number of Distinct Islands", "difficulty": "medium", "tags": ["graph", "dfs"]},
            {"title": "Minimum Spanning Tree using Prim's", "difficulty": "medium", "tags": ["graph", "heap"]},
            {"title": "Minimum Spanning Tree using Kruskal's", "difficulty": "medium", "tags": ["graph", "union-find"]},
            {"title": "Word Ladder", "difficulty": "hard", "tags": ["graph", "bfs"]},
            {"title": "Surrounded Regions", "difficulty": "medium", "tags": ["graph", "dfs"]},
            {"title": "Pacific Atlantic Water Flow", "difficulty": "medium", "tags": ["graph", "bfs", "dfs"]},
            {"title": "Number of Provinces", "difficulty": "medium", "tags": ["graph", "dfs", "union-find"]},
        ],
    },
    # =========================================================================
    # 13. Heap (15 problems)
    # =========================================================================
    {
        "topic": "Heap",
        "problems": [
            {"title": "Implement a MaxHeap MinHeap using arrays", "difficulty": "easy", "tags": ["heap", "design"]},
            {"title": "Sort an Array using Heap HeapSort", "difficulty": "medium", "tags": ["heap", "sorting"]},
            {"title": "Maximum of all subarrays of size K", "difficulty": "hard", "tags": ["heap", "sliding-window"]},
            {"title": "Kth Largest Element in an Array", "difficulty": "medium", "tags": ["heap", "array"]},
            {"title": "Kth Smallest Element in an Array", "difficulty": "medium", "tags": ["heap", "array"]},
            {"title": "Merge K Sorted Arrays", "difficulty": "medium", "tags": ["heap", "array"]},
            {"title": "Merge K Sorted Linked Lists", "difficulty": "hard", "tags": ["heap", "linked-list"]},
            {"title": "Find Median in a Stream", "difficulty": "hard", "tags": ["heap", "design"]},
            {"title": "Check if a Binary Tree is Heap", "difficulty": "medium", "tags": ["heap", "tree"]},
            {"title": "Convert BST to Min Heap", "difficulty": "medium", "tags": ["heap", "tree"]},
            {"title": "Convert Min Heap to Max Heap", "difficulty": "easy", "tags": ["heap"]},
            {"title": "Minimum Cost of Ropes", "difficulty": "easy", "tags": ["heap", "greedy"]},
            {"title": "Task Scheduler", "difficulty": "medium", "tags": ["heap", "greedy"]},
            {"title": "Smallest Range covering elements from K Lists", "difficulty": "hard", "tags": ["heap", "sliding-window"]},
            {"title": "Reorganize String", "difficulty": "medium", "tags": ["heap", "greedy", "string"]},
        ],
    },
    # =========================================================================
    # 14. Trie (7 problems)
    # =========================================================================
    {
        "topic": "Trie",
        "problems": [
            {"title": "Construct a Trie from Scratch", "difficulty": "medium", "tags": ["trie", "design"]},
            {"title": "Search and Insert in Trie", "difficulty": "medium", "tags": ["trie"]},
            {"title": "Word Break Problem using Trie", "difficulty": "medium", "tags": ["trie", "dynamic-programming"]},
            {"title": "Implement a Phone Directory using Trie", "difficulty": "medium", "tags": ["trie", "design"]},
            {"title": "Auto Complete Feature using Trie", "difficulty": "medium", "tags": ["trie", "design"]},
            {"title": "Implement Forward DNS Lookup Cache", "difficulty": "medium", "tags": ["trie", "design"]},
            {"title": "Implement Reverse DNS Lookup Cache", "difficulty": "medium", "tags": ["trie", "design"]},
        ],
    },
    # =========================================================================
    # 15. Dynamic Programming (60 problems)
    # =========================================================================
    {
        "topic": "Dynamic Programming",
        "problems": [
            {"title": "Coin Change Problem", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Knapsack Problem", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Binomial Coefficient", "difficulty": "medium", "tags": ["dynamic-programming", "math"]},
            {"title": "Permutation Coefficient", "difficulty": "medium", "tags": ["dynamic-programming", "math"]},
            {"title": "Nth Catalan Number", "difficulty": "medium", "tags": ["dynamic-programming", "math"]},
            {"title": "Matrix Chain Multiplication", "difficulty": "hard", "tags": ["dynamic-programming"]},
            {"title": "Edit Distance", "difficulty": "medium", "tags": ["dynamic-programming", "string"]},
            {"title": "Subset Sum Problem", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Friends Pairing Problem", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Gold Mine Problem", "difficulty": "medium", "tags": ["dynamic-programming", "matrix"]},
            {"title": "Assembly Line Scheduling", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Painting the Fence Problem", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Maximize The Cut Segments", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Longest Common Subsequence", "difficulty": "medium", "tags": ["dynamic-programming", "string"]},
            {"title": "Longest Increasing Subsequence", "difficulty": "medium", "tags": ["dynamic-programming", "binary-search"]},
            {"title": "Longest Common Substring", "difficulty": "medium", "tags": ["dynamic-programming", "string"]},
            {"title": "Longest Palindromic Subsequence", "difficulty": "medium", "tags": ["dynamic-programming", "string"]},
            {"title": "Minimum number of insertions to make a string palindrome", "difficulty": "medium", "tags": ["dynamic-programming", "string"]},
            {"title": "0/1 Knapsack Problem detailed", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Program for nth Fibonacci number", "difficulty": "easy", "tags": ["dynamic-programming"]},
            {"title": "Longest Alternating Subsequence", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Weighted Job Scheduling", "difficulty": "medium", "tags": ["dynamic-programming", "sorting"]},
            {"title": "Count number of binary strings without consecutive 1s", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Egg Dropping Problem", "difficulty": "hard", "tags": ["dynamic-programming"]},
            {"title": "Max length chain of pairs", "difficulty": "medium", "tags": ["dynamic-programming", "sorting"]},
            {"title": "Palindrome Partitioning Problem", "difficulty": "hard", "tags": ["dynamic-programming", "string"]},
            {"title": "Word Wrap Problem DP approach", "difficulty": "hard", "tags": ["dynamic-programming"]},
            {"title": "Maximum profit in rod cutting", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Dice Throw Problem", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Minimum cost to fill given weight in a bag", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Count Derangements", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Minimum number of jumps to reach end", "difficulty": "medium", "tags": ["dynamic-programming", "greedy"]},
            {"title": "Maximum Sum Increasing Subsequence", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Count number of hops", "difficulty": "easy", "tags": ["dynamic-programming"]},
            {"title": "Maximum sum without adjacents", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Staircase Problem", "difficulty": "easy", "tags": ["dynamic-programming"]},
            {"title": "Pairs with Specific Difference", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Minimum cost path in matrix", "difficulty": "medium", "tags": ["dynamic-programming", "matrix"]},
            {"title": "Maximum difference of zeros and ones in binary string", "difficulty": "medium", "tags": ["dynamic-programming", "string"]},
            {"title": "Boolean Parenthesization Problem", "difficulty": "hard", "tags": ["dynamic-programming"]},
            {"title": "Largest square sub-matrix with all 1s", "difficulty": "medium", "tags": ["dynamic-programming", "matrix"]},
            {"title": "Optimal Strategy for a Game", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Optimal Binary Search Tree", "difficulty": "hard", "tags": ["dynamic-programming", "tree"]},
            {"title": "Maximum path sum in matrix", "difficulty": "medium", "tags": ["dynamic-programming", "matrix"]},
            {"title": "Maximum profit from selling wines", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Longest Common Subsequence of three strings", "difficulty": "medium", "tags": ["dynamic-programming", "string"]},
            {"title": "Maximum sum rectangular sub-matrix in a 2D matrix", "difficulty": "hard", "tags": ["dynamic-programming", "matrix"]},
            {"title": "Longest Palindromic Substring DP", "difficulty": "medium", "tags": ["dynamic-programming", "string"]},
            {"title": "Count Palindromic Subsequences", "difficulty": "hard", "tags": ["dynamic-programming", "string"]},
            {"title": "nCr Problem", "difficulty": "easy", "tags": ["dynamic-programming", "math"]},
            {"title": "Mobile Numeric Keypad Problem", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Ugly Numbers", "difficulty": "medium", "tags": ["dynamic-programming", "math"]},
            {"title": "Maximum sum path in two arrays", "difficulty": "medium", "tags": ["dynamic-programming", "array"]},
            {"title": "Assembly Line Scheduling detailed", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Minimum number of deletions to make a string palindrome", "difficulty": "medium", "tags": ["dynamic-programming", "string"]},
            {"title": "Minimum number of deletions to make a sorted sequence", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Largest Divisible Pairs Subset", "difficulty": "medium", "tags": ["dynamic-programming", "sorting"]},
            {"title": "Longest subsequence such that difference is one", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Maximum size subset with given sum", "difficulty": "medium", "tags": ["dynamic-programming"]},
            {"title": "Longest Bitonic Subsequence", "difficulty": "medium", "tags": ["dynamic-programming"]},
        ],
    },
]


def _count_problems():
    """Count the total number of problems across all topics."""
    return sum(len(t["problems"]) for t in LOVE_BABBAR_450)


TOTAL_PROBLEMS = _count_problems()
